### ISSUE TITLE
Crash in BasicParser.m when running on background thread

### ISSUE THREAD

**Issue by edmw** [fkuehne/upnpx#35] opened 2014-10-19 18:16 UTC
After updating to 1.3.0 I'm constantly getting crashes in BasicParser.m when performing operations on a background thread (for example BrowseWithObjectID).

Most of the time: `EXC_BAD_ACCESS (code=1, address=0x18)` in line 92. Sometimes an exception is raised: `'NSGenericException', reason: '*** Collection <__NSArrayM: 0x7f986847a2d0> was mutated while being enumerated.'` in BasicParser getAssetForElementStack.

I can avoid this by executing the operation on main thread which renders my UI unresponsive.

**Comment by squarefrog** [comment] 2015-01-23 10:29
The issue here is that, as it states, you cannot mutate an `NSMutableArray` while using quick enumeration (`while`, `for in` loop etc). I can't immediately see any place where this is an issue in that method, and while I've seen a crash report of this in [Fabric](http://fabric.io) I can't figure out where the mutation is happening.

@edmw Are you able to give a list of steps to replicate the bug?

**Comment by fkuehne** [comment] 2015-01-23 17:26
@themachsystem I was not able to reproduce the issue using my deployment apps.

**Comment by squarefrog** [comment] 2015-01-27 10:20
I've just managed to reproduce this. Here is my scenario:

I have a view that displays the albums of a particular server. There are ~160 objects available to UPnP. I have a background fetch method, which fetches all objects in batches of 20 one after the other. If I interrupt this flow, by tapping on an album which triggers a fetch child call, then the exception gets raised.

I reproduced the issue twice, but it completely relies on timing to get it to crash. I find putting an `NSLog` statement inside `-[BasicParser parseFromData]` slows down the loop just long enough to improve the chances of reproducing the issue.

**Comment by squarefrog** [comment] 2015-02-09 14:37
Just found a way to consistently replicate this issue.

- Create an NSOperationQueue
- Create several NSBlockOperations, each which fetches some data from a upnp server (for example, batch fetch results from browse direct children)
- Ensure the operation queues number of concurrent queues is > 1
- Run code

The code is crashing as `mAssets` is mutated while its data is being looped through.

I've created a [basic project repo](https://github.com/squarefrog/upnpx-parserissue) that exhibits this behaviour. I find it's most easier produced with an older NAS drive running Twonky with A LOT of media. 

Run the app, navigate to a particularly long list (i.e. all music, or albums), and you should be able to reproduce.

**Comment by squarefrog** [comment] 2015-02-09 14:45
It should be noted that I don't know how the object is being mutated, I see nothing in the loop that is directly adding/removing (or you'd see the issue with synchronous stuff too).

A new parser seems to get created for each thread so that shouldn't be an issue either.

**Comment by squarefrog** [comment] 2015-02-18 15:09
OK this is more obvious now. When sending a browse request, the `SoapActionsContentDirectory` has an `mAssets` dictionary that is required for the parsing of the network request. 

When triggered from a separate queue, the new queue mutates `mAssets` as it is sending a different network request. 

If this occurs while parsing is currently in progress, a crash happens. Theres a fairly trivial fix, change [these lines](https://github.com/fkuehne/upnpx/blob/master/src/upnp/BasicParser.m#L89-L90)

    NSEnumerator *enumer = [mAssets objectEnumerator];
    while((asset = [enumer nextObject])){

to 

    NSArray *assets = [mAssets copy];
    NSEnumerator *enumer = [assets objectEnumerator];
    while((asset = [enumer nextObject])){

While this avoids crashes, it has the very real potential to return erroneous results. I think an option would be to monitor `mAssets` and abort parsing when it is altered, on the assumption that the last request is the most important, which may well be incorrect.

Ideally though, the most appropriate solution would be to ensure each parser instance has it's own `mAssets` dictionary.

**Comment by fkuehne** [comment] 2015-06-08 11:30
This should be fixed through increased locking on the parser :)

**Closed by fkuehne** 2015-06-08 11:30 UTC
Labels: bug
